### ISSUE TITLE
Crashes on run

### ISSUE THREAD

**Issue by dazhbog** [laffra/happymac#1] opened 2018-11-25 05:22 UTC
Heres the error log. Removed token.

```
HappyMac Available Versions:
['v00001', 'v00013']

HappyMac Activity Log:
    2018-11-25 05:15:32.143775: Download: getting the latest version at https://happymac.app/_functions/latest?version=v00001&uuid=
 
    2018-11-25 05:15:34.715801: Download: extracted version v00013 to /Users/poopy/HappyMacApp/downloads/v00013 
    2018-11-25 05:15:34.718335: Download: available versions: ['v00001', 'v00013'] 
    2018-11-25 05:15:34.718680: Find version v00013 
    2018-11-25 05:15:34.730409: Calling run on <module 'v00013' from '/var/folders/dn/qzdg_f3x6glfhr37xtjy9brr0000gn/T/tmpYbx2nt.py'> 
    2018-11-25 05:15:34.961188: Getting license from: https://www.happymac.app/_functions/agree/?token=XXXX
 
    2018-11-25 05:15:37.476398: Received license key:     XXXX
    2018-11-25 05:15:37.476821: Set preference license to u'XXX' 
    2018-11-25 05:15:37.486655: ERROR: Could not load version due to NSInvalidArgumentException - Class OC_PythonObject: no such selector: methodForSelector:. Loading built-in v00001 
    2018-11-25 05:15:37.486767: Find version v00001 
    2018-11-25 05:15:37.486948: Downloads: Could not find version v00001 in /Users/xxxxx/HappyMacApp/downloads/v00001 
    2018-11-25 05:15:37.487055: Calling run on <module 'versions.v00001.main' from '/var/folders/dn/qzdg_f3x6glfhr37xtjy9brr0000gn/T/_MEIDli2Vg/versions/v00001/main.pyc'> 

HappyMac Execution Stack at Error Time:
  File "happymac.py", line 10, in <module>

HappyMac Exception:
    Traceback (most recent call last):
  File "happymac.py", line 8, in <module>
  File "version_manager.py", line 39, in main
  File "version_manager.py", line 50, in load_version
  File "versions/v00001/main.py", line 239, in run
  File "versions/v00001/main.py", line 56, in __init__
  File "versions/v00001/main.py", line 161, in create_menu
ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such selector: methodForSelector:

HappyMac Error:
    Could not launch HappyMac
```

Hope this helps.

**Comment by laffra** [comment] 2018-11-25 13:00
This looks like an incarnation of https://github.com/jaredks/rumps/issues/2, which is a bug for rumps from 2014. It mentions rumps works fine with PyObjC 2.3.2a0. In the meantime, PyObjC is now at v5.5.1. That makes me wonder, what version of MacOS are you on? I personally have not tested HappyMac against any versions before 10.13 (High Sierra).

**Comment by laffra** [comment] 2018-12-29 17:01
Cannot reproduce. Closing this issue.

**Closed by laffra** 2018-12-29 17:01 UTC
